---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/pictures":
    post:
      summary: Upload Picture
      tags:
      - Picture
      parameters: []
      responses:
        '200':
          description: Uploads picture
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    example: the_url
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                picture:
                  type: object
                  properties:
                    image:
                      type: string
                      example: The Image
  "/api/v1/authenticated":
    get:
      summary: Checks if user is authenticated or not
      tags:
      - Auth
      responses:
        '200':
          description: signs in
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      authenticated:
                        type: boolean
                        example: true
  "/api/v1/users/sign_in":
    post:
      summary: Signs in
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: signs in
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      email:
                        type: string
                        example: sean.leannon@haag-oberbrunner.info
                      mobile:
                        type: string
                        example: "+975-17171717"
                      created_at:
                        type: string
                        example: '2022-01-20T17:40:12.492Z'
                      updated_at:
                        type: string
                        example: '2022-01-20T17:40:12.492Z'
                      profile_attributes:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: Alvin
                          address:
                            type: string
                            example: Some address
                          user_id:
                            type: integer
                            example: 1
                          created_at:
                            type: string
                            example: '2022-01-20T17:40:12.492Z'
                          updated_at:
                            type: string
                            example: '2022-01-20T17:40:12.492Z'
                      role_attributes:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: super_admin
                            enum:
                            - super_admin
                            - restuarant_owner
                          created_at:
                            type: string
                            example: '2022-01-20T17:40:12.492Z'
                          updated_at:
                            type: string
                            example: '2022-01-20T17:40:12.492Z'
        '401':
          description: Could not sign in
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      oneOf:
                      - type: string
                        example: Invalid Email or password.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: the email
                    password:
                      type: string
                      example: the password
  "/api/v1/users/sign_out":
    delete:
      summary: Signs Out
      tags:
      - Auth
      responses:
        '200':
          description: signs out
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Signed Out successfully
        '401':
          description: does not sign out
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      oneOf:
                      - type: string
                        example: You need to sign in or sign up before continuing.
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
